### ISSUE TITLE
module "bpy.utils" has no attribute "register_module"

### ISSUE THREAD

**Issue by Kllngii** [REDxEYE/io_mesh_SourceMDL#19]
I tried to install the plugin and I wasn't able to enable it.
I am using macOS 10.14.6 and blender 2.82a.

Here is the error:
<code>Modules Installed (io_mesh_SourceMDL-rewrite) from "{USER}/io_mesh_SourceMDL-rewrite.zip" into "{USER}/Library/Application Support/Blender/2.82/scripts/addons"

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/modules/addon_utils.py", line 382, in enable
    mod.register()
  File "{USER}/Library/Application Support/Blender/2.82/scripts/addons/io_mesh_SourceMDL-rewrite/__init__.py", line 119, in register
    bpy.utils.register_module(__name__)
AttributeError: module 'bpy.utils' has no attribute 'register_module'

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/modules/addon_utils.py", line 382, in enable
    mod.register()
  File "{USER}/Library/Application Support/Blender/2.82/scripts/addons/io_mesh_SourceMDL-rewrite/__init__.py", line 119, in register
    bpy.utils.register_module(__name__)
AttributeError: module "bpy.utils" has no attribute "register_module"

bpy.data.window_managers["WinMan"].addon_search = ""
Modules Installed (io_mesh_SourceMDL-rewrite) from "{USER}/BlenderAddons/io_mesh_SourceMDL-rewrite.zip" into "{USER}/Library/Application Support/Blender/2.82/scripts/addons"
Modules Installed (io_mesh_SourceMDL-rewrite) from "{USER}/BlenderAddons/io_mesh_SourceMDL-rewrite.zip" into "{USER}/Library/Application Support/Blender/2.82/scripts/addons"
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/modules/addon_utils.py", line 382, in enable
    mod.register()
  File "{USER}/Library/Application Support/Blender/2.82/scripts/addons/io_mesh_SourceMDL-rewrite/__init__.py", line 119, in register
    bpy.utils.register_module(__name__)
AttributeError: module "bpy.utils" has no attribute "register_module"
</code>

**Comment by Kllngii** [comment]
UPDATE: I just saw the 2.80 branch and its readme.md
