### ISSUE TITLE
ByteIO.OffsetOutOfBounds

### ISSUE THREAD

**Issue by Gnates** [REDxEYE/io_mesh_SourceMDL#9]
I tried to import mdls from this Steam Workshop Add-on for Garry's Mod:
- https://steamcommunity.com/sharedfiles/filedetails/?id=630707146
- Tested only Akasha and Ayumi models

I got the following error in Blender 2.79b (I believe this happens in 2.80 too):

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_mesh_SourceMDL-rewrite\__init__.py", line 40, in execute
    join_bones=self.normal_bones, join_clamped=self.join_clamped)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_mesh_SourceMDL-rewrite\io_Mdl.py", line 82, in __init__
    self.MDL = MDL.SourceMdlFile49(file_path)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_mesh_SourceMDL-rewrite\MDL.py", line 22, in __init__
    self.read_bones()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_mesh_SourceMDL-rewrite\MDL.py", line 48, in read_bones
    SourceMdlBone().read(self.reader, self.file_data)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_mesh_SourceMDL-rewrite\MDL_DATA.py", line 834, in read
    reader.read_ascii_string)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_mesh_SourceMDL-rewrite\ByteIO.py", line 195, in read_from_offset
    raise OffsetOutOfBounds()
io_mesh_SourceMDL-rewrite.ByteIO.OffsetOutOfBounds

location: <unknown location>:-1

**Comment by Gnates** [comment]
Here is a link to the 2 models: 
- https://www.sendspace.com/file/jocuap
You can also try this:
- https://steamcommunity.com/sharedfiles/filedetails/?id=124396380

Sorry, discord is acting up again, but I got your message.

**Comment by REDxEYE** [comment]
Probably incompatible version of MDL

**Comment by Gnates** [comment]
Alright.
Do you know which MDL versions will be supported?
The only versions I've tested, so far, that did not import are versions 44 and 48.

**Comment by REDxEYE** [comment]
48,49,53 should work

**Comment by REDxEYE** [comment]
44 isn't supported

**Comment by Gnates** [comment]
Blender 2.80 Beta Date: 2019-02-02 Hash: 4ef09cf937f2
io_mesh_SourceMDL: v2.1 (Feb 3rd 2019)

I tested this Postal 3 model (MDL v48 according to Crowbar):
- https://sta.sh/09oqflbli8o

I got the following error:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_mesh_SourceMDL-blender280\__init__.py", line 40, in execute
    join_bones=self.normal_bones, join_clamped=self.join_clamped)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_mesh_SourceMDL-blender280\io_Mdl.py", line 82, in __init__
    self.MDL = MDL.SourceMdlFile49(file_path)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_mesh_SourceMDL-blender280\MDL.py", line 32, in __init__
    self.read_bone_flex_drivers()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_mesh_SourceMDL-blender280\MDL.py", line 180, in read_bone_flex_drivers
    mouth.read(self.reader)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_mesh_SourceMDL-blender280\MDL_DATA.py", line 1597, in read
    self.bone = reader.read_int32()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_mesh_SourceMDL-blender280\ByteIO.py", line 159, in read_int32
    return self.read('i')
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_mesh_SourceMDL-blender280\ByteIO.py", line 143, in read
    return struct.unpack(t, self._read(size))[0]
struct.error: unpack requires a buffer of 4 bytes

location: <unknown location>:-1

The model does not import into the scene.

**Comment by REDxEYE** [comment]
Everything related to MDL versions will be fixed in next BIG refactor
